export { default as Avatar } from './Avatar'
export { default as Badge } from './Badge'
export { default as Logo } from './Logo'
export { default as Text } from './Text'
export { default as Upload } from './Upload'
